<a href="https://colab.research.google.com/github/Royalrival/Antariksh/blob/main/lec4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# PANDAS

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Numpy datatypes

# i-integer
# b-boolean
# u-unsigned integer
# f-float
# c-complex float
# m-timedelta
# M-datetime
# O-Object
# S-String
# U-Unicode string
# V-fix chunk or memory

# NUMPY

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
type(arr)
#Array object ndarray used

[1 2 3 4 5]


numpy.ndarray

In [6]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1.ndim)
arr2=np.array([[[1,2,4],[3,4,5],[7,2,5]]])
print(arr2.ndim)

2
3


In [7]:
arr3=np.array([1,867,368], dtype='f4')
arr3

array([  1., 867., 368.], dtype=float32)

In [8]:
print(arr2[0,1,2])
print(arr2[0,2,::1])

5
[7 2 5]


In [9]:
arr=np.array([2,8,9,3], dtype='f4')
print(arr)
newar=arr.astype(dtype='int64')
newar


[2. 8. 9. 3.]


array([2, 8, 9, 3])

In [10]:
newar=arr.copy()
arr[0]=5
print(arr)
print(newar)
#COPY AND VIEW- In copy the value if modified doesnt reflect in the copied array but in view it gets reflected on it


[5. 8. 9. 3.]
[2. 8. 9. 3.]


In [11]:
arr=np.array([65,87,99,12])
newar=arr.view()
arr[0]=5
print(arr)
print(newar)

[ 5 87 99 12]
[ 5 87 99 12]


In [12]:
arr1=np.array([7,8,9])
arr2=np.array([1,2,3])
arr=np.stack((arr1,arr2),axis=1)
arr
#Stack arranges it in a vertical orientation of each element, followed by the next array element at that position

array([[7, 1],
       [8, 2],
       [9, 3]])

In [13]:
arr1=np.array([[4,5,6],[1,2,3]])
arr2=np.array([[10,11,12],[7,8,9]])
arr=np.hstack((arr1,arr2))
arr
#hpstack arranges it in horizontal orientation where first array elements get concatenated with the other array elements

array([[ 4,  5,  6, 10, 11, 12],
       [ 1,  2,  3,  7,  8,  9]])

In [14]:
zeroarr=np.zeros((4,2), dtype='i4')
zeroarr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [15]:
print(arr.shape)
print(arr)

(2, 6)
[[ 4  5  6 10 11 12]
 [ 1  2  3  7  8  9]]


In [16]:
print(arr.reshape(6,2))

[[ 4  5]
 [ 6 10]
 [11 12]
 [ 1  2]
 [ 3  7]
 [ 8  9]]


In [17]:
art1 = np.array([1,2,3,4])

for i in art1:
  print(i)

1
2
3
4


In [18]:
arr5=np.array([[1,3,5,7],[2,4,6,8]])
arr6=np.array([[1,4,7,10],[2,5,8,11]])
arr=np.concatenate((arr5,arr6))
arr

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [19]:
ab=np.arange(7,15)
ab

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(5,10,5)
lspace

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [21]:
print(arr.T)

[[ 1  2  1  2]
 [ 3  4  4  5]
 [ 5  6  7  8]
 [ 7  8 10 11]]


In [22]:
#to calculate inverse use linalg.inv function
ar=np.array([[2,4],[3,7]])
print(np.linalg.inv(ar))


[[ 3.5 -2. ]
 [-1.5  1. ]]


In [23]:
print(ar.sum(axis=0))
#in axis=0 it clculates sum rowwise
print(ar.sum(axis=1))
#in axis=1 it clculates sum colunwise

[ 5 11]
[ 6 10]


In [24]:
#argmax shows maximum index position
#max shows the maximum value
ar.argmax()


3

In [25]:
ar.max()

7

In [26]:
#argsort sorts element indexes in matrix and only sort sorts the elements
ar.argsort()

array([[0, 1],
       [0, 1]])

In [29]:
arr0=np.array([32,12,8,37,81,9])
print(np.sort(arr0))

[ 8  9 12 32 37 81]


In [30]:
#Search sort

In [31]:
#filtering
arr = np.array([11,12,13,14])
x = [True,False,True,False]
newarr = arr[x]
newarr

array([11, 13])

In [33]:
#COnditioned filtering
filter_a = []
arr = np.array([12,17,15,21,18,13])

for element in arr:
  if(element>17):
    filter_a.append(True)
  else:
    filter_a.append(False)

new_arr = arr[filter_a]
new_arr

array([21, 18])

In [34]:
#Using where func
marks = np.array([18,65,49,93,17,73,46,82])
passed = ['pass','pass','pass','pass','pass','pass','pass','pass',]
failed = ['fail','fail','fail','fail','fail','fail','fail','fail',]

newarr = np.where((marks>30) & (marks<50),passed,failed)
newarr

array(['fail', 'fail', 'pass', 'fail', 'fail', 'fail', 'pass', 'fail'],
      dtype='<U4')